// Generated by CoffeeScript 2.2.4
(function() {
  var BotServant;

  BotServant = class BotServant {
    constructor(botApi, identifier, botName, botID) {
      this.botApi = botApi;
      this.identifier = identifier;
      this.botName = botName;
      this.botID = botID;
    }

    processUpdate(update) {}

  };

  module.exports = BotServant;

}).call(this);
